### ISSUE TITLE
npm error

### ISSUE THREAD

**Issue by AlanBacker** [hihumanzone/Gemini-Discord-Bot#4]
root~# git clone https://github.com/hihumanzone/Gemini-Discord-Bot.git
Cloning into 'Gemini-Discord-Bot'...
remote: Enumerating objects: 713, done.
remote: Counting objects: 100% (346/346), done.
remote: Compressing objects: 100% (165/165), done.
remote: Total 713 (delta 219), reused 280 (delta 181), pack-reused 367
Receiving objects: 100% (713/713), 2.95 MiB | 9.88 MiB/s, done.
Resolving deltas: 100% (403/403), done.
root:~# cd Gemini-Discord-Bot/
root:~/Gemini-Discord-Bot# npm install dotenv node-fetch@2.6.7 discord.js @google/generative-ai fs sharp pdf-parse cheerio youtube-transcript axios eventsource node-os-utils @google/generative-ai/files
npm error code ENOENT
npm error syscall open
npm error path /root/Gemini-Discord-Bot/@google/generative-ai/files/package.json
npm error errno -2
npm error enoent Could not read package.json: Error: ENOENT: no such file or directory, open '/root/Gemini-Discord-Bot/@google/generative-ai/files/package.json'
npm error enoent This is related to npm not being able to find a file.
npm error enoent
npm error A complete log of this run can be found in: /root/.npm/_logs/2024-06-28T08_54_06_758Z-debug-0.log

Here's the log
[2024-06-28T08_54_06_758Z-debug-0.log](https://github.com/user-attachments/files/16026996/2024-06-28T08_54_06_758Z-debug-0.log)

**Comment by hihumanzone** [comment]
I think I fixed it, could you please try again now and confirm if it's fixed?

**Comment by AlanBacker** [comment]
yes the problem has been fixed, thank you and have a nice day.
