### ISSUE TITLE
[Bug report]Bot Overloaded

### ISSUE THREAD

**Issue by AlanBacker** [hihumanzone/Gemini-Discord-Bot#8]
<img width="482" alt="image" src="https://github.com/user-attachments/assets/0f6147cb-a0a5-4fc5-bf40-8fa8b5246971">
<img width="1161" alt="image" src="https://github.com/user-attachments/assets/70320fea-7673-4812-948e-68c001d3dd6a">
As you can see, this is the problem.
When I try to send messages to the bot, it always responds with "Bot Overloaded".

**Comment by hihumanzone** [comment]
Update the code and try again; there was a typo 😵‍💫

**Comment by AlanBacker** [comment]
> Update the code and try again; there was a typo 😵‍💫

Fixed, thanks!
