### ISSUE TITLE
web search errors

### ISSUE THREAD

**Issue by lima12** [hihumanzone/Gemini-Discord-Bot#9]
step to replicate: 
1. ask the bot to perform websearch
2. look at console
`error while performing web search: Error: Failed to perform the search request: getaddrinfo ENOTFOUND search.neuranet-ai.com`

![image](https://github.com/user-attachments/assets/4348a3e9-503d-4520-a810-eb93b542d372)

**Comment by lima12** [comment]
https://neuranet-ai.com/ well look like they shutting down

**Comment by lima12** [comment]
Here a temp fix for this issue. 
Here what you need:

- google custom search apikey which can be obtain via [google developers page](https://developers.google.com/custom-search/v1/overview)
- google custom search cx id (search engine ID) which would be locate [here](https://programmablesearchengine.google.com/controlpanel/all)


`async function performSearch(query) {
  const apiKey = 'replace-this'; 
  const cx = 'replace-this-too';
  const url = `https://www.googleapis.com/customsearch/v1?q=${encodeURIComponent(query)}&key=${apiKey}&cx=${cx}`;

  try {
    const response = await axios.get(url);
    const entries = response.data.items; 

    if (Array.isArray(entries)) {
      const resultObject = entries.slice(0, 5).map((entry, index) => {
        const title = entry.title;
        const result = entry.snippet;
        const url = entry.link;

        return {
          [`result_${index + 1}`]: { title, result, url }
        };
      });

      const note = {
        "Note": "Search results provide only an overview and do not offer sufficiently detailed information. Please continue by using the Search Website tool and search websites to find relevant information about the topic."
      };

      const finalResult = JSON.stringify(
        resultObject.reduce((acc, curr) => Object.assign(acc, curr), note),
        null,
        2
      );

      /*console.log(finalResult); //For debug purpose only!*/
      return finalResult;

    } else {
      console.error('Entries is not an array:', entries);
      throw new Error('Unexpected response format');
    }
  } catch (error) {
    console.error('Request failed:', error.response?.data || error.message);
    throw new Error(`Failed to perform the search request: ${error.message}`);
  }
}
`

This isn't official solution! im just a scripty pasta dude.

**Comment by hihumanzone** [comment]
Oh, that's a bummer! My friend was the CEO of this company, and I've quit Discord due to exams. I'll try searching for another source, and if I don't find any, I'll just use this Google one, for sure.

**Comment by hihumanzone** [comment]
I THINK I HAD A ALTERNATIVE.. wait 💀

**Comment by hihumanzone** [comment]
https://github.com/hihumanzone/Gemini-OpenAI-web-search-function-call/blob/3beabef58bc585eb60c0959abc4918c70d24509a/Gemini_s.js#L186C29-L186C29 

found it :))

let's see if it works..

**Comment by hihumanzone** [comment]
I've updated the GitHub code, thanks for reporting the issue. The reason I'm not using the Google search API is that it requires an API key, and I don't want users to have to provide an additional API key beyond the one for Google Generative AI.

**Comment by lima12** [comment]
Great! thank you
